### PR TITLE
Plot solutions in notebook about number with uncertainties

### PR DESCRIPTION
**Pull request by giordano**
The latest version of `Measurements.jl` supports `Plots.jl` and I took the occasion to update the related tutorial to show this feature (actually, I decided to implement this feature exactly for this tutorial).

Only problem is that it doesn't seem to be possible to simply do `plot(sol)`, I get some errors.  Any idea why?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
`plot(sol)` isn't working because of the uncertainty units in the time axis. Here's an example of what it's trying to plot:

```julia
plot_vecs = Array{Measurements.Measurement{Float64},2}[Measurements.Measurement{Float64}[0.0±0.0 0.0±0.0; 0.7±0.0 0.7±0.0; 1.4±0.0 1.4±0.0; 2.1±0.0 2.1±0.0; 2.8±0.0 2.8±0.0; 3.5±0.0 3.5±0.0; 4.2±0.0 4.2±0.0; 4.9±0.0 4.9±0.0; 5.6±0.0 5.6±0.0; 6.3±0.0 6.3±0.0], Measurements.Measurement{Float64}[0.0±0.0 0.0523599±0.01; 0.0136252±0.00260833 -0.030399±0.00582552; -0.0158215±0.00302163 -0.0170628±0.003441; 0.00474627±0.00104186 0.0502153±0.00960169; 0.0103102±0.00207155 -0.041252±0.00800825; -0.0167209±0.00319506 -0.00230837±0.00295728; 0.0091089±0.00195622 0.0439434±0.00860254; 0.006143±0.00171479 -0.0487269±0.00942984; -0.0162466±0.00313255 0.0126454±0.00515169; 0.0127256±0.00263903 0.0340415±0.00763667]]
```

It's then trying to plot things like `plot(plot_vecs[1][:,1],plot_vecs[2][:,1]); plot(plot_vecs[1][:,2],plot_vecs[2][:,2])`. It's failing because `plot_vecs[1]` has (trivial) uncertainty. The fix is to do:

```julia
plot(Measurements.value.(plot_vecs[1])[:,1],plot_vecs[2])
```

Could you add this recipe that you can plot Measurements x Measurements if the first measurements are trivial by converting it to the values?

**Comment by ChrisRackauckas** [comment]
The fact that it hits the analytical solution of not just the values but the uncertainties as well: is that known or expected?

**Comment by giordano** [comment]
> It's then trying to plot things like `plot(plot_vecs[1][:,1],plot_vecs[2][:,1]); plot(plot_vecs[1][:,2],plot_vecs[2][:,2])`. It's failing because `plot_vecs[1]` has (trivial) uncertainty.

Sorry, I don't follow you here.  It shouldn't fail trying to plot `plot(plot_vecs[1][:,1],plot_vecs[2][:,1]); plot(plot_vecs[1][:,2],plot_vecs[2][:,2])`, and it doesn't fail for me if I try it.  Am I missing something?

These are the recipes I defined in the package: https://github.com/JuliaPhysics/Measurements.jl/blob/ba37969434f0f48d887abe1f3066a5cd15a85c39/src/plot-recipes.jl  The value is always returned, the uncertainties are just used as errorbars.  How should I extend them?

> The fact that it hits the analytical solution of not just the values but the uncertainties as well: is that known or expected?

Are you asking whether it's expected that the uncertainties of analytic solution exactly match those of the numerical solution?  If so, the answer is "of course yes!".  If correlation wasn't taken into account properly you'd get the first plot, the one with completely wrong errorbars.

**Comment by ChrisRackauckas** [comment]
Oh, it's because your recipe must handle vectors but not matrices:

```julia
> plot(value.(plot_vecs[1]),value.(plot_vecs[2]))

> plot(plot_vecs[1],plot_vecs[2])
ERROR: MethodError: Cannot `convert` an object of type Measurements.Measurement{Float64} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] expand_extrema!(::Plots.Extrema, ::Measurements.Measurement{Float64}) at C:\Users\Chris\.julia\v0.6\Plots\src\axes.jl:303
 [2] expand_extrema!(::Plots.Axis, ::Array{Measurements.Measurement{Float64},1}) at C:\Users\Chris\.julia\v0.6\Plots\src\axes.jl:326
 [3] expand_extrema!(::Plots.Subplot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}) at C:\Users\Chris\.julia\v0.6\Plots\src\axes.jl:356
 [4] _expand_subplot_extrema(::Plots.Subplot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Symbol) at C:\Users\Chris\.julia\v0.6\Plots\src\pipeline.jl:364
 [5] _process_seriesrecipe(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}) at C:\Users\Chris\.julia\v0.6\Plots\src\pipeline.jl:400
 [6] _plot!(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Measurements.Measurement{Float64},2},Array{Measurements.Measurement{Float64},2}}) at C:\Users\Chris\.julia\v0.6\Plots\src\plot.jl:235
 [7] #plot#212(::Array{Any,1}, ::Function, ::Array{Measurements.Measurement{Float64},2}, ::Vararg{Array{Measurements.Measurement{Float64},2},N} where N) at C:\Users\Chris\.julia\v0.6\Plots\src\plot.jl:58
 [8] plot(::Array{Measurements.Measurement{Float64},2}, ::Array{Measurements.Measurement{Float64},2}, ::Vararg{Array{Measurements.Measurement{Float64},2},N} where N) at C:\Users\Chris\.julia\v0.6\Plots\src\plot.jl:52
```

>Are you asking whether it's expected that the uncertainties of analytic solution exactly match those of the numerical solution? If so, the answer is "of course yes!". If correlation wasn't taken into account properly you'd get the first plot, the one with completely wrong errorbars. The tutorial shows that the solver exactly reproduces the behavior of the analytic function, also with its errorbars.

So someone proved that an adaptive ODE solver will converge to the analytical solution plus error bars of linear error propogation theory?

**Comment by giordano** [comment]
> Oh, it's because your recipe must handle vectors but not matrices:

Yesterday I tried to replace all "Vector" in the recipes with "Array", but I still get the same error when trying to plot `sol`.  However, with this change I can do `plot(plot_vecs[1],plot_vecs[2])` and it works as expected

> So someone proved that an adaptive ODE solver will converge to the analytical solution plus error bars of linear error propogation theory?

I've never found such proof (I'm not saying it doesn't exist, though!), but it shouldn't be too hard to formalize.  According to the linear error propagation theory, the uncertainty on `f(a, b,...)`, with `a` and `b` independent, is
```
\sqrt(((\partial f)/(\partial a) * \sigma_a)^ 2 + ((\partial f)/(\partial b) * \sigma_b)^ 2 + ...)
```
that is, the Euclidean norm of the Hadamard (element-wise) product between the gradient of `f` with respect to the set of variables and the vector of uncertainties of the same variables in the same order.

Thus, if the ODE solver converges to a function which has the same differential properties as the true solution (which should be the case for an ODE solver ;-), the numerical solution will also have the same uncertainties

**Comment by ChrisRackauckas** [comment]
>Yesterday I tried to replace all "Vector" in the recipes with "Array", but I still get the same error when trying to plot sol. However, with this change I can do plot(plot_vecs[1],plot_vecs[2]) and it works as expected

Is this change somewhere I can checkout? The recipe ends by just returning

```julia
(plot_vecs...)
```

so essentially the diffeq solution recipe returns that tuple of plot vectors for Plots.jl to then handle, which presumably calls your recipe. If it's not getting to there I can help find out why.

**Comment by giordano** [comment]
> Is this change somewhere I can checkout?

[`v0.5.x`](https://github.com/JuliaPhysics/Measurements.jl/tree/v0.5.x) branch in the repo.  Thank you!

**Comment by ChrisRackauckas** [comment]
I'm still having an issue:

```julia
> using Measurements
INFO: Recompiling stale cache file C:\Users\Chris\.julia\lib\v0.6\Measurements.ji for module Measurements.

> plot_vecs = Array{Measurements.Measurement{Float64},2}[Measurements.Measurement{Float64}[0.0±0.0 0.0±0.0; 0.7±0.0 0.7±0.0; 1.4±0.0 1.4±0.0; 2.1±0.0 2.1±0.0; 2.8±0.0 2.8±0.0; 3.5±0.0 3.5±0.0; 4.2±0.0 4.2±0.0; 4.9±0.0 4.9±0.0; 5.6±0.0 5.6±0.0; 6.3±0.0 6.3±0.0], Measurements.Measurement{Float64}[0.0±0.0 0.0523599±0.01; 0.0136252±0.00260833 -0.030399±0.00582552; -0.0158215±0.00302163 -0.0170628±0.003441; 0.00474627±0.00104186 0.0502153±0.00960169; 0.0103102±0.00207155 -0.041252±0.00800825; -0.0167209±0.00319506 -0.00230837±0.00295728; 0.0091089±0.00195622 0.0439434±0.00860254; 0.006143±0.00171479 -0.0487269±0.00942984; -0.0162466±0.00313255 0.0126454±0.00515169; 0.0127256±0.00263903 0.0340415±0.00763667]]
2-element Array{Array{Measurements.Measurement{Float64},2},1}:
 Measurements.Measurement{Float64}[0.0±0.0 0.0±0.0; 0.7±0.0 0.7±0.0; … ; 5.6±0.0 5.6±0.0; 6.3±0.0 6.3±0.0]                                                      
 Measurements.Measurement{Float64}[0.0±0.0 0.0523599±0.01; 0.0136252±0.00260833 -0.030399±0.00582552; … ; -0.0162466±0.00313255 0.0126454±0.00515169; 0.0127256±0.00263903 0.0340415±0.00763667]

> plot(plot_vecs)
ERROR: UndefVarError: plot not defined

> using Plots; plotly()
INFO: Recompiling stale cache file C:\Users\Chris\.julia\lib\v0.6\PlotUtils.ji for module PlotUtils.
INFO: Recompiling stale cache file C:\Users\Chris\.julia\lib\v0.6\Plots.ji for module Plots.
Plots.PlotlyBackend()

> plot(plot_vecs)
ERROR: MethodError: Cannot `convert` an object of type Measurements.Measurement{Float64} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] expand_extrema!(::Plots.Extrema, ::Measurements.Measurement{Float64}) at C:\Users\Chris\.julia\v0.6\Plots\src\axes.jl:303
 [2] expand_extrema!(::Plots.Axis, ::Array{Measurements.Measurement{Float64},1}) at C:\Users\Chris\.julia\v0.6\Plots\src\axes.jl:326
 [3] expand_extrema!(::Plots.Subplot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}) at C:\Users\Chris\.julia\v0.6\Plots\src\axes.jl:356
 [4] _expand_subplot_extrema(::Plots.Subplot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Symbol) at C:\Users\Chris\.julia\v0.6\Plots\src\pipeline.jl:364
 [5] _process_seriesrecipe(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}) at C:\Users\Chris\.julia\v0.6\Plots\src\pipeline.jl:400
 [6] _plot!(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Array{Measurements.Measurement{Float64},2},1}}) at C:\Users\Chris\.julia\v0.6\Plots\src\plot.jl:235
 [7] plot(::Array{Array{Measurements.Measurement{Float64},2},1}) at C:\Users\Chris\.julia\v0.6\Plots\src\plot.jl:52

> Pkg.status("Measurements")
 - Measurements                  0.5.1+             v0.5.x
```

**Comment by giordano** [comment]
That's the same error I get. I got this error also on v0.5.1 of Measurements.jl, without the change to the recipes

**Comment by ChrisRackauckas** [comment]
Maybe it needs a recipe to de-structure the tuple? I always thought Plots re-splatted those though, but that must be a recipe.

```julia
typeof((plot_vecs...,)) = Tuple{Array{Measurements.Measurement{Float64},2},Array{Measurements.Measurement{Float64},2}}
```

that's the type it's returning.

**Comment by giordano** [comment]
I don't think that's the issue, also `plot((plot_vecs...,))` does work for me on that branch.

I've just tried to add this recipe:
```julia
@recipe function f(x::AbstractArray{<:AbstractArray{<:Measurement}})
    @assert length(x) == 2
    xerror := uncertainty.(x[1])
    yerror := uncertainty.(x[2])
    value.(x[1]), value.(x[2])
end
```

This makes `plot(plot_vecs)` work, but `plot(sol)` still doesn't work:
```julia
julia> plot(sol)
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: MethodError: Cannot `convert` an object of type Measurements.Measurement{Float64} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
```
There isn't even a stacktrace, it's hard to understand where's the culprit.

**Comment by giordano** [comment]
Great you found out what was the problem!

However, for the sake of this tutorial, where I'd like to show a simple visual comparison with the analytic solution, probably a continuous plot is not useful.

Probably a ribbon plot would be better, and it's definitely a good idea for the future with Makie.

**Comment by ChrisRackauckas** [comment]
I'll merge for now and we should keep this in mind.

**Pull request merged**
