### PR TITLE
Add DynamicalODEProblem and NBodyProblems example

### PR DESCRIPTION
**Pull request by YingboMa**
This plot looks insane!

screenshot from 2017-08-26 03-56-37

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Get rid of the checkpoints

**Comment by ChrisRackauckas** [comment]
You might want to mention that the reason why you're seeing more drift out of the RKN method is because it's low order. High order methods are drifting, but they are simply drifting less because they are more accurate.

**Comment by ChrisRackauckas** [comment]
Can you add examples with `ManifoldProjection`?

**Comment by YingboMa** [comment]
Oh, I actually don't know how to use the `ManifoldProjection`.

**Comment by ChrisRackauckas** [comment]
Read the docs and ask questions if you don't get it. Then we can update the docs 👍.

**Comment by YingboMa** [comment]
The docs is crystal clear :diamond_shape_with_a_dot_inside: , but `nlsolve` doesn't support `RecursiveArrayTools.ArrayPartition` type. :crying_cat_face: 

```julia
MethodError: no method matching nlsolve(::NLsolve.DifferentiableMultivariateFunction, ::RecursiveArrayTools.ArrayPartition{Float64,Tuple{Array{Float64,1},Array{Float64,1}}})
```

Minimal reproducible example:

```julia
using OrdinaryDiffEq, DiffEqCallbacks
H(q,p) = norm(p)^2/2 - inv(norm(q))
L(q,p) = q[1]*p[2] - p[1]*q[2]

qdot(t,q,p,dq) = ForwardDiff.gradient!(dq, p-> H(q, p), p)
pdot(t,q,p,dq) = ForwardDiff.gradient!(dq, q->-H(q, p), q)
initial_position = [.4, 0]
initial_velocity = [0., 2.]
tspan = (0,20.)
prob = DynamicalODEProblem(qdot,pdot, initial_position, initial_velocity, tspan)
initial_first_integrals = (H(sol.u[1].x...), L(sol.u[1].x...))

function first_integrals_manifold(u, residual)
    residual[1] = initial_first_integrals[1] - H(u.x...)
    residual[2] = initial_first_integrals[2] - L(u.x...)
end

cb = ManifoldProjection(first_integrals_manifold)
sol5 = solve(prob, Tsit5(), callback=cb)
analysis_plot(sol5, H, L)
```

**Comment by ChrisRackauckas** [comment]
Can you show it on `Vern` with problems defined on arrays?

**Comment by ChrisRackauckas** [comment]
LGTM. Merge when you think it's ready.

**Pull request merged**
