### PR TITLE
updated kepler problem tutorial

### PR DESCRIPTION
**Pull request by Mikhail-Vaganov**
1. Corrected arguments order in calls of `qdot` and `pdot`.
2. There are different orders of variables `u` and `v`  in `ODEProblem` and `DynamicalODEProblem`. Moreover, I guess, the order was changed at some time of these problems' existence. I have updated the plotting functions with the current state of things.
3. Small remark: it seems like in the [documentation ](http://docs.juliadiffeq.org/latest/types/dynamical_types.html) a wrong order of `u` and `v` variables noted in the declaration of `f1` and `f2`.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
>Small remark: it seems like in the documentation a wrong order of u and v variables noted in the declaration of f1 and f2.

Thanks. Just fix. Yes, that argument change has been disastrous for the documentation, but things seem almost smooth now... almost...

**Comment by ChrisRackauckas** [comment]
>There are different orders of variables u and v in ODEProblem and DynamicalODEProblem. Moreover, I guess, the order was changed at some time of these problems' existence. I have updated the plotting functions with the current state of things.

Just for the info, there was a gigantic change to the argument ordering of almost everything in January described here:

http://juliadiffeq.org/2018/01/24/Parameters.html

Of course, all tests pass, but there's some docs that got left behind. That seems to be what you ran into.

**Comment by Mikhail-Vaganov** [comment]
Ok, thanks, I will check it.

**Comment by Mikhail-Vaganov** [comment]
A little bit more regarding components order.

As for me, there is a slight inconsistency:
solution of the `ODEProblem`: arrays of `[u; v]` components 
solution of the `DynamicalODEProblem`: arrays of `[v,u]`

Certainly, we can rearrange the array of variables for an `ODEProblem` so that it contains velocities in the beginning and coordinates in the end. But even considering arbitrary variables `u` and `v` such as `v=du/dt` I think, usually, people expect `u` going first and before `v` in arrays. Probably I am wrong and I am just used to this order myself. I ran into the same situation using `SecondOrderODEProblem` where `v`s go before `u`s in solutions.

What do you think about that?

**Comment by ChrisRackauckas** [comment]
>Certainly, we can rearrange the array of variables for an ODEProblem so that it contains velocities in the beginning and coordinates in the end. But even considering arbitrary variables u and v such as v=du/dt I think, usually, people expect u going first and before v in arrays. Probably I am wrong and I am just used to this order myself. I ran into the same situation using SecondOrderODEProblem where vs go before us in solutions.

Yes, it should both be `v` then `u`. That order is chosen because `du` needs to be in front so that way the modified variable is always first, but then that establishes `du,u` as the common order, i.e. derivatives first, so by extension `ddu,du,u` for second order or `dv,v,u`. 

From this code:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/problems/ode_problems.jl#L36-L83

the derivatives always seem to go first. 

>solution of the ODEProblem: arrays of [u; v] components

If that's actually happening when it lowers, that's an accident and should be corrected, but I don't see why that would be the case. Are you not talking about the automatic promotion of `SecondOrderODEProblem` to `ODEProblem`?

**Comment by ChrisRackauckas** [comment]
BTW, here's the tests for OrdinaryDiffEq.jl:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/partitioned_methods_tests.jl

There may be a doc issue: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/partitioned_methods_tests.jl#L5-L10 the velocity function should be going first in all cases. If it's not doing that somewhere in the docs, then the docs need to be updated.

**Comment by Mikhail-Vaganov** [comment]
> Are you not talking about the automatic promotion of SecondOrderODEProblem to ODEProblem

No-no, just about the interface. I was writing as an end-user trying to solve the same mechanic problem using two different approaches: via `ODEProblem` and `SecondOrderODEProblem`.

>  That order is chosen because du needs to be in front so that way the modified variable is always first, but then that establishes du,u as the common order, i.e. derivatives first, so by extension ddu,du,u for second order or dv,v,u.

Now it makes sense for me, thank you. Yes, it is logical.

>then the docs need to be updated
If I notice an issue, should I report it somewhere or just make a pull request to `DiffEqDocs.jl`?

**Comment by ChrisRackauckas** [comment]
Great, looks like that's all cleared up now. Thanks!

**Pull request merged**
