### PR TITLE
DEBio tutorial II and templating of css/latex

### PR DESCRIPTION
**Pull request by isaacsas**
This PR does a few things:

1. Tweaks the first DEBio tutorial to always use the new API.
2. Adds a second tutorial exploring the API. It shows how to use accessor functions, use the min/empty reaction network macros, how to incrementally generate a network, how to then add ODEs/SDEs/jumps to that network, and concludes with a 1D diffusion example showing how to incrementally construct and solve ODE and jump models.
3. I copied in a Latex template from Weave, and slightly modified it to include the mhchem environment package (needed by Latexify).
4. I copied in the css template from Weave, and modified it to center images in generated html files.
5. I add the ability to pass kwargs to the `weave` function. This allowed me to pass kwargs to use the css/latex templates, and to specify svg images for the html/notebook files.

Note, none of these changes should at all influence the other tutorials -- to use the templates one must explicitly pass them as kwargs when calling the weave function.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
There's only 1 jmd in here?

**Comment by isaacsas** [comment]
Two jmds. Tutorial I was updated and tutorial II was added. So two tutorials = 10 files, and then the css file, html template, tex template, README and the update to add kwargs to weave.

**Comment by ChrisRackauckas** [comment]
Oh it wasn't expanded.

**Comment by ChrisRackauckas** [comment]
Should we use the modified template in `weave_all`?

**Comment by isaacsas** [comment]
It probably makes sense. For latex it just adds one line including the mhchem package, which allows Latexify to work (outside of tex documents, where one also has to set `mathjax=false`). 

The css template just makes figures centered in the generated html, which I find a bit nicer. If I remember right it might also increase their default size a bit too.

**Comment by ChrisRackauckas** [comment]
The CSS template sounds nice. I think for a lot of future updates we will likely just `weave_all` here and there, so it would be good to have that working. Or at least some other way to fix that.

**Comment by isaacsas** [comment]
I need to make a small tweak to the second tutorial when we next release DiffEqBio, so can update everything to use the templates at that time.

**Pull request merged**
