### PR TITLE
Typos, slight rearranging and one problem

### PR DESCRIPTION
**Pull request by KZiemian**
I propose rearranging of text in cell to be more divided with accordance to topics.

Description of interpolation algorithm looks a bit outdated to me.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
The notebooks are not the source of this repo. They are a product of the .jmd files. These edits should be made to https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/tutorials/introduction/ode_introduction.jmd

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaDiffEq/DiffEqTutorials.jl#contributing

**Comment by KZiemian** [comment]
Thank you for information and I apologized for the problem. Mu stupid excuses is that, there is some many computer technologies, that I still cannot wrap my head arround one really good, I must learn something new.

I have a question if you don't mind. Why in "Contribution'' there is `Pkg.pkg"activate ."` without parenthesis?

**Comment by ChrisRackauckas** [comment]
Are parenthesis needed?

**Comment by ChrisRackauckas** [comment]
A bit out of date.

**Pull request closed without merging**
