### PR TITLE
Edit Bayesian inference tutorial

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
The previous one had unidentifiable parameters. This changes the parameters to be identifiable, and uses likelihoods so the result is non-trivial. However, this exposes a bug.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@xukai92 @Vaibhavdixit02 can we take a look at the Bayesian inference stuff today and fix this? The means don't seem to budge from the priors.

**Comment by Vaibhavdixit02** [comment]
Using Normal distribution seems to have this problem, I think the prior becomes too dominant in that case. Using an Uniform distribution gives better result

**Comment by ChrisRackauckas** [comment]
Being that sensitive to the prior is a problem. This should be a simple example.

**Comment by ChrisRackauckas** [comment]
The issue was the sampler. The default `IS` sampler was really bad, so I changed the default to a No U-Turn sampler and it trained just fine.

**Pull request merged**
